IO_OPTION:
  INPUT_ROOT: '/media/hiroki/working/research/dcase2020/datasets/DCASE2'
  OUTPUT_ROOT: '/media/hiroki/working/research/dcase2020/baseline_code/mlflow_test'
  TB_OUTPATH: '/media/hiroki/working/research/dcase2020/result/train/tbx/mlflow_test'
  MLFLOW_PATH: '/media/hiroki/working/research/dcase2020/result/train/mlflow'
  # 'ToyCar' or 'ToyConveyor' or  'fan' or 'pump' or 'slider' or 'valve' or 'run_all'
  MACHINE_TYPE: 'run_all'
  # for log
  model_name: 'Deep_AutoEncoder'
  
mel_spectrogram_param:
  n_mels: 128
  frames : 5
  n_fft: 1024
  hop_length: 512
  power: 2.0

fit:
  batch_size : 512
  shuffle : True
  num_epochs : 1
  devise : 'cuda'

etc:
  test_size : 0.3
