IO_OPTION:
  INPUT_ROOT: '/media/hiroki/working/research/dcase2020/datasets/DCASE2'
  OUTPUT_ROOT: '/media/hiroki/working/research/dcase2020/result/VAE/VAE_1D_z10'
  MLFLOW_PATH: '/media/hiroki/working/research/dcase2020/result/train_eval_mlflow'
  # 'ToyCar' or 'ToyConveyor' or  'fan' or 'pump' or 'slider' or 'valve' or 'run_all'
  MACHINE_TYPE: 'run_all'
  # for log
  model_name: 'VAE_z10'

mel_spectrogram_param:
  n_mels: 128
  frames : 5
  n_fft: 1024
  hop_length: 512
  power: 2.0

fit:
  batch_size : 512
  shuffle : True
  num_epochs : 100
  devise : 'cuda'

etc:
  test_size : 0.1
  max_fpr : 0.1
