IO_OPTION:
  INPUT_ROOT: '/media/hiroki/working/research/dcase2020/datasets/DCASE2'
  OUTPUT_ROOT: '/media/hiroki/working/research/dcase2020/result/2D/CONV_AE_debug'
  MLFLOW_PATH: '/media/hiroki/working/research/dcase2020/result/train/mlflow'
  PREMODEL_PATH: '/media/hiroki/working/research/dcase2020/pre-trained_model/Cnn6_mAP=0.343.pth'
  # 'ToyCar' or 'ToyConveyor' or  'fan' or 'pump' or 'slider' or 'valve' or 'run_all'
  MACHINE_TYPE: 'run_all'
  # for log
  model_name: 'PANNsCNN14_AE'
  
preprocessing:
  sample_rate: 16000
  mono: True
  mel_bins: 64
  fmin: 50
  fmax: 8000
  window_size: 512
  hop_size: 160
  window: 'hann'
  pad_mode: 'reflect'
  center: True
　ref: 1.0
　amin: 1e-10
　top_db: None

  #frames : 5
  #n_fft: 1024
  #hop_length: 512
  #power: 2.0

fit:
  batch_size : 32
  shuffle : True
  num_epochs : 100
  devise : 'cuda'

etc:
  test_size : 0.3
  max_fpr : 0.1



