IO_OPTION:
  INPUT_ROOT: '/media/hiroki/working/research/dcase2020/datasets/DCASE2'
  OUTPUT_ROOT: './output'
  MLFLOW_PATH: './output'
  # 'ToyCar' or 'ToyConveyor' or  'fan' or 'pump' or 'slider' or 'valve' or 'run_all'
  MACHINE_TYPE: 'run_all'
  # for log
  model_name: 'Deep_AutoEncoder_debug'
  
mel_spectrogram_param:
  n_mels: 128
  frames : 5
  n_fft: 1024
  hop_length: 512
  power: 2.0

fit:
  batch_size : 16
  shuffle : True
  num_epochs : 100
  devise : 'cuda'

etc:
  test_size : 0.3
  max_fpr : 0.1
